# .tekton/tasks.yml

# ----------------------------
# Task 1: Cleanup Task (Task 4)
# ----------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: busybox
      script: |
        #!/bin/sh
        echo "🧹 Cleaning workspace and old artifacts..."
        rm -rf /workspace/source/data/*
        rm -rf /workspace/source/models/*
        echo "✅ Cleanup complete."

---

# ----------------------------
# Task 2: Nose Test Task (Task 5)
# ----------------------------
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-nose-tests
      image: python:3.10
      workingDir: /workspace/source
      script: |
        #!/bin/bash
        echo "🚀 Starting Nose Test Task..."
        pip install --upgrade pip
        pip install nose
        pip install -r requirements.txt
        echo "✅ Running ML pipeline using nose..."
        nosetests app.py --nocapture || python app.py
        echo "✅ Task completed successfully!"
